"""empty message

Revision ID: 0a4549f021b9
Revises: 2d1c7797d49e
Create Date: 2017-05-31 12:04:49.970279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a4549f021b9'
down_revision = '2d1c7797d49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'appeals_ibfk_2', 'appeals', type_='foreignkey')
    op.drop_constraint(u'appeals_ibfk_3', 'appeals', type_='foreignkey')
    op.drop_column('appeals', 'module_id')
    op.drop_column('appeals', 'table_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('appeals', sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'appeals_ibfk_3', 'appeals', 'table', ['table_id'], ['id'])
    op.create_foreign_key(u'appeals_ibfk_2', 'appeals', 'module', ['module_id'], ['id'])
    # ### end Alembic commands ###
