"""empty message

Revision ID: 0b82fd49988a
Revises: 0a4549f021b9
Create Date: 2017-05-31 12:25:03.375789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b82fd49988a'
down_revision = '0a4549f021b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appeals', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_server_default=sa.text(u"'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appeals', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_server_default=sa.text(u"'1'"))
    # ### end Alembic commands ###
