"""empty message

Revision ID: 0d1ea8f79019
Revises: 78fde15cb750
Create Date: 2017-05-05 15:18:14.672578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1ea8f79019'
down_revision = '78fde15cb750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'module_ibfk_1', 'module', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'module_ibfk_1', 'module', 'user', ['name'], ['id'])
    # ### end Alembic commands ###
