"""empty message

Revision ID: 2030b605625c
Revises: c81836a325c5
Create Date: 2017-05-25 11:02:33.136929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2030b605625c'
down_revision = 'c81836a325c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'history_ibfk_2', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'user', ['user_id'], ['id'])
    op.add_column('module', sa.Column('url', sa.String(length=15), nullable=True))
    op.drop_constraint(u'permission_ibfk_1', 'permission', type_='foreignkey')
    op.create_foreign_key(None, 'permission', 'role', ['role_id'], ['id'])
    op.drop_constraint(u'user_ibfk_3', 'user', type_='foreignkey')
    op.drop_constraint(u'user_ibfk_2', 'user', type_='foreignkey')
    op.drop_constraint(u'user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_ibfk_1', 'user', 'post', ['post_id'], ['id'], ondelete=u'SET NULL')
    op.create_foreign_key(u'user_ibfk_2', 'user', 'role', ['role_id'], ['id'], ondelete=u'SET NULL')
    op.create_foreign_key(u'user_ibfk_3', 'user', 'department', ['department_id'], ['id'], ondelete=u'SET NULL')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.create_foreign_key(u'permission_ibfk_1', 'permission', 'role', ['role_id'], ['id'], ondelete=u'SET NULL')
    op.drop_column('module', 'url')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(u'history_ibfk_2', 'history', 'user', ['user_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###
