"""empty message

Revision ID: 2d1c7797d49e
Revises: e022ce8ee143
Create Date: 2017-05-31 08:53:48.599368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1c7797d49e'
down_revision = 'e022ce8ee143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.Column('ddate', sa.DateTime(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'history_ibfk_2', 'history', type_='foreignkey')
    op.create_foreign_key(None, 'history', 'user', ['user_id'], ['id'])
    op.drop_constraint(u'important_news_ibfk_1', 'important_news', type_='foreignkey')
    op.create_foreign_key(None, 'important_news', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'important_news', type_='foreignkey')
    op.create_foreign_key(u'important_news_ibfk_1', 'important_news', 'user', ['author'], ['id'], onupdate=u'CASCADE')
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.create_foreign_key(u'history_ibfk_2', 'history', 'user', ['user_id'], ['id'], onupdate=u'CASCADE')
    op.drop_table('appeals')
    # ### end Alembic commands ###
