"""empty message

Revision ID: 4ab07cb896ef
Revises: 0b82fd49988a
Create Date: 2017-06-02 08:09:39.453507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab07cb896ef'
down_revision = '0b82fd49988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'answer')
    # ### end Alembic commands ###
