"""empty message

Revision ID: 733fcb88f548
Revises: d4b3a5caff08
Create Date: 2017-04-24 11:29:56.187534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733fcb88f548'
down_revision = 'd4b3a5caff08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('opis', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'opis')
    # ### end Alembic commands ###
