"""empty message

Revision ID: cee44ca60050
Revises: 532b6ada73bc
Create Date: 2017-05-10 08:35:21.133602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee44ca60050'
down_revision = '532b6ada73bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('url', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'url')
    # ### end Alembic commands ###
