"""empty message

Revision ID: d766b715ca55
Revises: 
Create Date: 2017-06-08 10:53:32.836091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd766b715ca55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_kartoteka():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('filename', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade_kartoteka():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'filename')
    # ### end Alembic commands ###

