"""empty message

Revision ID: d90934894429
Revises: 733fcb88f548
Create Date: 2017-04-24 11:30:21.286742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd90934894429'
down_revision = '733fcb88f548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'opis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('opis', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
