"""empty message

Revision ID: e022ce8ee143
Revises: e07eee080abb
Create Date: 2017-05-29 09:04:03.883468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e022ce8ee143'
down_revision = 'e07eee080abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('comment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'comment')
    # ### end Alembic commands ###
